"""LLM 直接生成の公平採点：表層一致(char n-gram)でなく、生成式と正解式の
物理的・数学的「等価性」を LLM(Opus 4.8)で審査して Recall@K_correct を測り直す。

- 生成式（method 側）は既存の Sonnet 4.5 生成（llm_set_*_predictions.json）を再利用。
- 採点(審査)のみ Opus 4.8。各正解式について、生成式リスト(優先順)の中で等価な式の
  順位を返させ、retrieval と同じ「上位 K 件で正解式をどれだけ被覆できたか」で Recall@K。
- baseline/reranker は DB の式をそのまま返す＝自己等価なので採点不変（再計算不要）。

出力: experiments/llm_{label}_fair_results.json
"""
from __future__ import annotations
import json, os, re, sys, time
from pathlib import Path

import numpy as np
from dotenv import load_dotenv

ROOT = Path(__file__).parent
load_dotenv(ROOT / ".env", override=True)
import anthropic

sys.path.insert(0, str(ROOT))
from set_aware_reranker import load_equations, load_cases, eq_key, norm

JUDGE_MODEL = "claude-opus-4-8"   # 採点(審査)用。最上位モデルで等価性を正確に判定
LABELS = ["set_full", "set_A", "set_B"]

JUDGE_PROMPT = """You are an expert chemical/physical-engineering examiner. Judge whether a list of CANDIDATE equations (generated by another model) covers each REQUIRED ground-truth equation.

Two equations are EQUIVALENT if they express the SAME physical/mathematical relationship, allowing for: different variable names/symbols, algebraic rearrangement (e.g. multiplying both sides by a variable), total vs partial derivative notation (d vs \\partial), and equivalent rewritten forms. They are NOT equivalent if they describe different physics, omit or add an essential term, or use materially different numerical constants.

REQUIRED equations (ground truth), numbered 1..{nreq}:
{required}

CANDIDATE equations (model-generated, priority order 1..{ncand}):
{candidate}

For each REQUIRED equation in order, output the index of the FIRST CANDIDATE that is equivalent to it, or 0 if none is equivalent. A candidate index may cover at most one required equation; if it could match several, assign it to the earliest and use 0 for the others (unless a different distinct candidate also matches).

Output ONLY a JSON array of exactly {nreq} integers, e.g. [1,0,3]. No prose, no code fences."""


def judge(client, required_tex, candidate_tex):
    n = len(required_tex)
    if not candidate_tex:
        return [0] * n
    req = "\n".join(f"{i+1}. {e}" for i, e in enumerate(required_tex))
    cand = "\n".join(f"{i+1}. {e}" for i, e in enumerate(candidate_tex))
    prompt = JUDGE_PROMPT.format(nreq=n, ncand=len(candidate_tex), required=req, candidate=cand)
    for attempt in range(4):
        try:
            resp = client.messages.create(model=JUDGE_MODEL, max_tokens=400,
                                          messages=[{"role": "user", "content": prompt}])
            txt = "".join(b.text for b in resp.content if b.type == "text")
            m = re.search(r"\[[\d,\s]*\]", txt)
            arr = json.loads(m.group(0)) if m else []
            arr = [int(x) for x in arr][:n]
            arr += [0] * (n - len(arr))
            return arr
        except anthropic.RateLimitError:
            time.sleep(20 * (attempt + 1))
        except Exception as e:
            print("  judge err", type(e).__name__, str(e)[:90]); time.sleep(3)
    return [0] * n


def recall_at_k(ranks, K):
    """ranks: 各正解式について等価な生成式の順位(0=未生成)。重複候補は先勝ちで除外。"""
    seen, ded = set(), []
    for g in ranks:
        if g > 0 and g in seen:
            ded.append(0)
        else:
            ded.append(g)
            if g > 0:
                seen.add(g)
    cov = sum(1 for g in ded if 1 <= g <= K)
    return cov / K, ded


def main():
    eqs = load_equations(); cases = load_cases()
    eqtext = {eq_key(e): (e.get("equation") or "") for e in eqs}
    by_id = {c.get("case_id"): c for c in cases}
    client = anthropic.Anthropic(api_key=os.environ["ANTHROPIC_API_KEY"])

    for label in LABELS:
        preds = json.load(open(ROOT / "experiments" / f"llm_{label}_predictions.json"))
        per_case = []
        for i, p in enumerate(preds):
            c = by_id.get(p["case_id"])
            if not c:
                continue
            req_tex = [eqtext[norm(m)] for m in (c.get("correct_model_ids") or [])
                       if eqtext.get(norm(m))]
            if not req_tex:
                continue
            cand_tex = [e.get("equation", "") for e in p.get("predictions", []) if e.get("equation")]
            ranks = judge(client, req_tex, cand_tex)
            K = len(req_tex)
            rk, ded = recall_at_k(ranks, K)
            per_case.append({"case_id": p["case_id"], "n_correct": K,
                             "Recall@K_correct": rk, "ranks": ded})
            print(f"  [{label} {i+1}/{len(preds)}] {p['case_id']} K={K} R@K={rk:.2f}")
            time.sleep(0.3)
        mean = float(np.mean([r["Recall@K_correct"] for r in per_case])) if per_case else 0.0
        out = ROOT / "experiments" / f"llm_{label}_fair_results.json"
        json.dump({"method": "claude_direct_generation_fairjudge", "judge": JUDGE_MODEL,
                   "n_cases": len(per_case), "Recall@K_correct": mean, "per_case": per_case},
                  open(out, "w"), ensure_ascii=False, indent=2)
        print(f"== {label}: 公平採点 Recall@K = {mean:.3f} (n={len(per_case)}) -> {out}")


if __name__ == "__main__":
    main()
